### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by dajare** [standardebooks/p-g-wodehouse_jeeves-stories#15]
I haven't checked page scans (given the sources) but this looks like an obvious case of missing punctuation:

*For*: an onion You might | *Read*: an onion. You might

(Add full stop/period after "onion".)

https://github.com/standardebooks/p-g-wodehouse_jeeves-stories/blob/bbfb72dc1d4010aff2310f9149ca4fa0374c51d4/src/epub/text/bertie-changes-his-mind.xhtml#L35

**Comment by acabal** [comment]
Thanks, this should be fixed now!
