### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/p-g-wodehouse_jeeves-stories#19]
"...reading for some exam, or other with the vicar."

(the comma should probably be omitted)

https://github.com/standardebooks/p-g-wodehouse_jeeves-stories/blob/70dcb5c6f9fc51c57e6220ce8925cf037d4a7131/src/epub/text/the-great-sermon-handicap.xhtml#L29

**Comment by acabal** [comment]
@b-t-k Can you take a look at this?

**Comment by b-t-k** [comment]
@acabal The Strand version has a period there (I assume as exam is an abbreviation). The Cosmopolitan version omitted it altogether.

**Comment by acabal** [comment]
OK, we'll remove it. Thanks!
